language: python
script: true
deploy:
  provider: pypi
  user: dimorinny
  password:
    secure: AgiJLyEAlB4NE7XJOI6qeFtcCbqyD8PVFsH2QL+hlH9cNd27Y+FxAUcQcB3OdCqo+DVEEangJAFxBUAszD0Icn2MtHzgn4EgkYRhBaQEiQxh07/S5/PKNjVBLB1MFzcXWwp44iltoaZLKlZJSh0LLXj2vf06jaKZet1e7HSSCztc6/N9ac2gjcDyzLBBzHFMEbcwdbxu/YsgbtbiUkVf3qJ21Vc1LBPzrausR895nVFoe1hKQZIq0sLuT6puW/dlRgw/2unZOyNCC/AGpzAyEgOMl+DS3KnJ9l97GKT9kq9m0d5P4kfpSQJZAPjiGmLAQSALFBsmCbN7xTRi+w5xeKDeCc7PI9BX1T7hR66MFHyMBaGUxX+e96hh/0xYbwZz9zGAxvOc9y6FIlYVVMOnAPMXgLCIB+giQc23VEF/HA1Z2JbGCUSclQcWd0x9o4uRIjMG8tK/VmEu+tQf5S0sjEtd3zvdP9wSmu0r9Xm/2cae/cSVSeritMM4AVtb066wE9Jx4G2qKW8nDrM9wqenxnEhA+R0yvXDSr/vqwCQTLHo1Snqyhcwjd55tn5/H9A/du4vn3sJlw50/WlPE5mV6Y+ZLk8K274+UcRmga34z0xyRlYR4IfQD0iEMS/MioR0cllrB/StLZyz1sIWwpievd8mvYO/V4YuEPLgUdYboxI=
